version: "3.9"
services:
  antibot-developer-trainee:
    image: antibot-developer-trainee:latest
    build:
      target: app
      dockerfile: Dockerfile
      context: .
    environment:
      PORT: "8080"
      LIMIT: "10"
      INTERVAL: "5s"
      BLOCKING_TIMEOUT: "30s"
    ports:
      - "8080:8080"
  prometheus:
    image: prom/prometheus:v2.24.0
    volumes:
      - ./devops/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

volumes:
  prometheus_data:
